### ISSUE TITLE
Xtreme 2

### ISSUE THREAD

**Issue by JeeDeeGD** [pembem22/jbl-firmware#2]
Hi, could you add jbl xtreme 2 QCC 2.3.0 file so we can get our LFM back?

**Comment by pembem22** [comment]
I don't have any firmware files earlier than 2.6.0 for Xtreme 2 QCC. It's possible that they simply don't exist because QCC version of the speaker was released later than CSR and firmware development started from version 2.6.0.

I limited firmware flashing to CSR only because I haven't been able to test it nor I know any successful case. You can try flashing with ConnectPlus v1.1.3, there's no such limit there and flashing tab will be available, but I can't guarantee it will work.

**Comment by JeeDeeGD** [comment]
I'm pretty sure that software before 2.6.0 exists on the QCC version, cause if I remember correctly I had updated from some version to 2.6.0 and then to 2.7.0 later.
Sucks that they removed LFM on the xtreme 2 newer software.

> I don't have any firmware files earlier than 2.6.0 for Xtreme 2 QCC. It's possible that they simply don't exist because QCC version of the speaker was released later than CSR and firmware development started from version 2.6.0.
> 
> I limited firmware flashing to CSR only because I haven't been able to test it nor I know any successful case. You can try flashing with ConnectPlus v1.1.3, there's no such limit there and flashing tab will be available, but I can't guarantee it will work.
